/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OrderRouteImport } from './routes/order'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as ProductProductRouteImport } from './routes/product.$product'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthProfileRouteImport } from './routes/api/auth/profile'
import { Route as ApiAuthSendOtpRouteImport } from './routes/api/auth/send-otp'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth/verify'
import { Route as ApiInventoryPurchaseRouteImport } from './routes/api/inventory/purchase'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductRoute = ProductProductRouteImport.update({
  id: '/product/$product',
  path: '/product/$product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSendOtpRoute = ApiAuthSendOtpRouteImport.update({
  id: '/api/auth/send-otp',
  path: '/api/auth/send-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryPurchaseRoute = ApiInventoryPurchaseRouteImport.update({
  id: '/api/inventory/purchase',
  path: '/api/inventory/purchase',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$product': typeof ProductProductRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/inventory/purchase': typeof ApiInventoryPurchaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$product': typeof ProductProductRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/inventory/purchase': typeof ApiInventoryPurchaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$product': typeof ProductProductRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/auth/send-otp': typeof ApiAuthSendOtpRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/inventory/purchase': typeof ApiInventoryPurchaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/order'
    | '/category/$category'
    | '/product/$product'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/auth/send-otp'
    | '/api/auth/verify'
    | '/api/inventory/purchase'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/order'
    | '/category/$category'
    | '/product/$product'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/auth/send-otp'
    | '/api/auth/verify'
    | '/api/inventory/purchase'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/order'
    | '/category/$category'
    | '/product/$product'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/auth/send-otp'
    | '/api/auth/verify'
    | '/api/inventory/purchase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  OrderRoute: typeof OrderRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ProductProductRoute: typeof ProductProductRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthProfileRoute: typeof ApiAuthProfileRoute
  ApiAuthSendOtpRoute: typeof ApiAuthSendOtpRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
  ApiInventoryPurchaseRoute: typeof ApiInventoryPurchaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$product': {
      id: '/product/$product'
      path: '/product/$product'
      fullPath: '/product/$product'
      preLoaderRoute: typeof ProductProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/send-otp': {
      id: '/api/auth/send-otp'
      path: '/api/auth/send-otp'
      fullPath: '/api/auth/send-otp'
      preLoaderRoute: typeof ApiAuthSendOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/purchase': {
      id: '/api/inventory/purchase'
      path: '/api/inventory/purchase'
      fullPath: '/api/inventory/purchase'
      preLoaderRoute: typeof ApiInventoryPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  OrderRoute: OrderRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ProductProductRoute: ProductProductRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthProfileRoute: ApiAuthProfileRoute,
  ApiAuthSendOtpRoute: ApiAuthSendOtpRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
  ApiInventoryPurchaseRoute: ApiInventoryPurchaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
