/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as OrderRouteImport } from './routes/order'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as CategoryCategoryRouteImport } from './routes/category.$category'
import { Route as ProductProductRouteImport } from './routes/product.$product'
import { Route as ApiAccountMeRouteImport } from './routes/api/account/me'
import { Route as ApiAccountWishlistRouteImport } from './routes/api/account/wishlist'
import { Route as ApiAdminInventoryRouteImport } from './routes/api/admin/inventory'
import { Route as ApiAdminOverviewRouteImport } from './routes/api/admin/overview'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthProfileRouteImport } from './routes/api/auth/profile'
import { Route as ApiInventoryPurchaseRouteImport } from './routes/api/inventory/purchase'
import { Route as ApiAdminAuthLoginRouteImport } from './routes/api/admin/auth/login'
import { Route as ApiAdminAuthLogoutRouteImport } from './routes/api/admin/auth/logout'
import { Route as ApiAdminAuthMeRouteImport } from './routes/api/admin/auth/me'
import { Route as ApiAdminAuthSetupRouteImport } from './routes/api/admin/auth/setup'
import { Route as ApiAdminAuthStatusRouteImport } from './routes/api/admin/auth/status'
import { Route as ApiAdminBrandsIndexRouteImport } from './routes/api/admin/brands/index'
import { Route as ApiAdminBrandsBrandIdRouteImport } from './routes/api/admin/brands/$brandId'
import { Route as ApiAdminCategoriesIndexRouteImport } from './routes/api/admin/categories/index'
import { Route as ApiAdminCategoriesCategoryIdRouteImport } from './routes/api/admin/categories/$categoryId'
import { Route as ApiAdminCategoriesReorderRouteImport } from './routes/api/admin/categories/reorder'
import { Route as ApiAdminInventoryMovementIdRouteImport } from './routes/api/admin/inventory/$movementId'
import { Route as ApiAdminProductsIndexRouteImport } from './routes/api/admin/products/index'
import { Route as ApiAdminProductsProductIdRouteImport } from './routes/api/admin/products/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderRoute = OrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const CategoryCategoryRoute = CategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductRoute = ProductProductRouteImport.update({
  id: '/product/$product',
  path: '/product/$product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountMeRoute = ApiAccountMeRouteImport.update({
  id: '/api/account/me',
  path: '/api/account/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountWishlistRoute = ApiAccountWishlistRouteImport.update({
  id: '/api/account/wishlist',
  path: '/api/account/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInventoryRoute = ApiAdminInventoryRouteImport.update({
  id: '/api/admin/inventory',
  path: '/api/admin/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOverviewRoute = ApiAdminOverviewRouteImport.update({
  id: '/api/admin/overview',
  path: '/api/admin/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfileRoute = ApiAuthProfileRouteImport.update({
  id: '/api/auth/profile',
  path: '/api/auth/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryPurchaseRoute = ApiInventoryPurchaseRouteImport.update({
  id: '/api/inventory/purchase',
  path: '/api/inventory/purchase',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthLoginRoute = ApiAdminAuthLoginRouteImport.update({
  id: '/api/admin/auth/login',
  path: '/api/admin/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthLogoutRoute = ApiAdminAuthLogoutRouteImport.update({
  id: '/api/admin/auth/logout',
  path: '/api/admin/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthMeRoute = ApiAdminAuthMeRouteImport.update({
  id: '/api/admin/auth/me',
  path: '/api/admin/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthSetupRoute = ApiAdminAuthSetupRouteImport.update({
  id: '/api/admin/auth/setup',
  path: '/api/admin/auth/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthStatusRoute = ApiAdminAuthStatusRouteImport.update({
  id: '/api/admin/auth/status',
  path: '/api/admin/auth/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBrandsIndexRoute = ApiAdminBrandsIndexRouteImport.update({
  id: '/api/admin/brands/',
  path: '/api/admin/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBrandsBrandIdRoute = ApiAdminBrandsBrandIdRouteImport.update({
  id: '/api/admin/brands/$brandId',
  path: '/api/admin/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesIndexRoute = ApiAdminCategoriesIndexRouteImport.update({
  id: '/api/admin/categories/',
  path: '/api/admin/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesCategoryIdRoute =
  ApiAdminCategoriesCategoryIdRouteImport.update({
    id: '/api/admin/categories/$categoryId',
    path: '/api/admin/categories/$categoryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminCategoriesReorderRoute =
  ApiAdminCategoriesReorderRouteImport.update({
    id: '/api/admin/categories/reorder',
    path: '/api/admin/categories/reorder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminInventoryMovementIdRoute =
  ApiAdminInventoryMovementIdRouteImport.update({
    id: '/$movementId',
    path: '/$movementId',
    getParentRoute: () => ApiAdminInventoryRoute,
  } as any)
const ApiAdminProductsIndexRoute = ApiAdminProductsIndexRouteImport.update({
  id: '/api/admin/products/',
  path: '/api/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProductsProductIdRoute =
  ApiAdminProductsProductIdRouteImport.update({
    id: '/api/admin/products/$productId',
    path: '/api/admin/products/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/profile': typeof ProfileRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$product': typeof ProductProductRoute
  '/api/account/me': typeof ApiAccountMeRoute
  '/api/account/wishlist': typeof ApiAccountWishlistRoute
  '/api/admin/inventory': typeof ApiAdminInventoryRouteWithChildren
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/inventory/purchase': typeof ApiInventoryPurchaseRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/auth/me': typeof ApiAdminAuthMeRoute
  '/api/admin/auth/setup': typeof ApiAdminAuthSetupRoute
  '/api/admin/auth/status': typeof ApiAdminAuthStatusRoute
  '/api/admin/brands/$brandId': typeof ApiAdminBrandsBrandIdRoute
  '/api/admin/categories/$categoryId': typeof ApiAdminCategoriesCategoryIdRoute
  '/api/admin/categories/reorder': typeof ApiAdminCategoriesReorderRoute
  '/api/admin/inventory/$movementId': typeof ApiAdminInventoryMovementIdRoute
  '/api/admin/products/$productId': typeof ApiAdminProductsProductIdRoute
  '/api/admin/brands/': typeof ApiAdminBrandsIndexRoute
  '/api/admin/categories/': typeof ApiAdminCategoriesIndexRoute
  '/api/admin/products/': typeof ApiAdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/profile': typeof ProfileRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$product': typeof ProductProductRoute
  '/api/account/me': typeof ApiAccountMeRoute
  '/api/account/wishlist': typeof ApiAccountWishlistRoute
  '/api/admin/inventory': typeof ApiAdminInventoryRouteWithChildren
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/inventory/purchase': typeof ApiInventoryPurchaseRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/auth/me': typeof ApiAdminAuthMeRoute
  '/api/admin/auth/setup': typeof ApiAdminAuthSetupRoute
  '/api/admin/auth/status': typeof ApiAdminAuthStatusRoute
  '/api/admin/brands/$brandId': typeof ApiAdminBrandsBrandIdRoute
  '/api/admin/categories/$categoryId': typeof ApiAdminCategoriesCategoryIdRoute
  '/api/admin/categories/reorder': typeof ApiAdminCategoriesReorderRoute
  '/api/admin/inventory/$movementId': typeof ApiAdminInventoryMovementIdRoute
  '/api/admin/products/$productId': typeof ApiAdminProductsProductIdRoute
  '/api/admin/brands': typeof ApiAdminBrandsIndexRoute
  '/api/admin/categories': typeof ApiAdminCategoriesIndexRoute
  '/api/admin/products': typeof ApiAdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/order': typeof OrderRoute
  '/profile': typeof ProfileRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/setup': typeof AdminSetupRoute
  '/category/$category': typeof CategoryCategoryRoute
  '/product/$product': typeof ProductProductRoute
  '/api/account/me': typeof ApiAccountMeRoute
  '/api/account/wishlist': typeof ApiAccountWishlistRoute
  '/api/admin/inventory': typeof ApiAdminInventoryRouteWithChildren
  '/api/admin/overview': typeof ApiAdminOverviewRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/profile': typeof ApiAuthProfileRoute
  '/api/inventory/purchase': typeof ApiInventoryPurchaseRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/auth/me': typeof ApiAdminAuthMeRoute
  '/api/admin/auth/setup': typeof ApiAdminAuthSetupRoute
  '/api/admin/auth/status': typeof ApiAdminAuthStatusRoute
  '/api/admin/brands/$brandId': typeof ApiAdminBrandsBrandIdRoute
  '/api/admin/categories/$categoryId': typeof ApiAdminCategoriesCategoryIdRoute
  '/api/admin/categories/reorder': typeof ApiAdminCategoriesReorderRoute
  '/api/admin/inventory/$movementId': typeof ApiAdminInventoryMovementIdRoute
  '/api/admin/products/$productId': typeof ApiAdminProductsProductIdRoute
  '/api/admin/brands/': typeof ApiAdminBrandsIndexRoute
  '/api/admin/categories/': typeof ApiAdminCategoriesIndexRoute
  '/api/admin/products/': typeof ApiAdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/categories'
    | '/contact'
    | '/order'
    | '/profile'
    | '/admin/categories'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/products'
    | '/admin/setup'
    | '/category/$category'
    | '/product/$product'
    | '/api/account/me'
    | '/api/account/wishlist'
    | '/api/admin/inventory'
    | '/api/admin/overview'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/inventory/purchase'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/auth/me'
    | '/api/admin/auth/setup'
    | '/api/admin/auth/status'
    | '/api/admin/brands/$brandId'
    | '/api/admin/categories/$categoryId'
    | '/api/admin/categories/reorder'
    | '/api/admin/inventory/$movementId'
    | '/api/admin/products/$productId'
    | '/api/admin/brands/'
    | '/api/admin/categories/'
    | '/api/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/categories'
    | '/contact'
    | '/order'
    | '/profile'
    | '/admin/categories'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/products'
    | '/admin/setup'
    | '/category/$category'
    | '/product/$product'
    | '/api/account/me'
    | '/api/account/wishlist'
    | '/api/admin/inventory'
    | '/api/admin/overview'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/inventory/purchase'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/auth/me'
    | '/api/admin/auth/setup'
    | '/api/admin/auth/status'
    | '/api/admin/brands/$brandId'
    | '/api/admin/categories/$categoryId'
    | '/api/admin/categories/reorder'
    | '/api/admin/inventory/$movementId'
    | '/api/admin/products/$productId'
    | '/api/admin/brands'
    | '/api/admin/categories'
    | '/api/admin/products'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/categories'
    | '/contact'
    | '/order'
    | '/profile'
    | '/admin/categories'
    | '/admin/inventory'
    | '/admin/login'
    | '/admin/products'
    | '/admin/setup'
    | '/category/$category'
    | '/product/$product'
    | '/api/account/me'
    | '/api/account/wishlist'
    | '/api/admin/inventory'
    | '/api/admin/overview'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/profile'
    | '/api/inventory/purchase'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/auth/me'
    | '/api/admin/auth/setup'
    | '/api/admin/auth/status'
    | '/api/admin/brands/$brandId'
    | '/api/admin/categories/$categoryId'
    | '/api/admin/categories/reorder'
    | '/api/admin/inventory/$movementId'
    | '/api/admin/products/$productId'
    | '/api/admin/brands/'
    | '/api/admin/categories/'
    | '/api/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  OrderRoute: typeof OrderRoute
  ProfileRoute: typeof ProfileRoute
  CategoryCategoryRoute: typeof CategoryCategoryRoute
  ProductProductRoute: typeof ProductProductRoute
  ApiAccountMeRoute: typeof ApiAccountMeRoute
  ApiAccountWishlistRoute: typeof ApiAccountWishlistRoute
  ApiAdminInventoryRoute: typeof ApiAdminInventoryRouteWithChildren
  ApiAdminOverviewRoute: typeof ApiAdminOverviewRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthProfileRoute: typeof ApiAuthProfileRoute
  ApiInventoryPurchaseRoute: typeof ApiInventoryPurchaseRoute
  ApiAdminAuthLoginRoute: typeof ApiAdminAuthLoginRoute
  ApiAdminAuthLogoutRoute: typeof ApiAdminAuthLogoutRoute
  ApiAdminAuthMeRoute: typeof ApiAdminAuthMeRoute
  ApiAdminAuthSetupRoute: typeof ApiAdminAuthSetupRoute
  ApiAdminAuthStatusRoute: typeof ApiAdminAuthStatusRoute
  ApiAdminBrandsBrandIdRoute: typeof ApiAdminBrandsBrandIdRoute
  ApiAdminCategoriesCategoryIdRoute: typeof ApiAdminCategoriesCategoryIdRoute
  ApiAdminCategoriesReorderRoute: typeof ApiAdminCategoriesReorderRoute
  ApiAdminProductsProductIdRoute: typeof ApiAdminProductsProductIdRoute
  ApiAdminBrandsIndexRoute: typeof ApiAdminBrandsIndexRoute
  ApiAdminCategoriesIndexRoute: typeof ApiAdminCategoriesIndexRoute
  ApiAdminProductsIndexRoute: typeof ApiAdminProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order': {
      id: '/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof OrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/category/$category': {
      id: '/category/$category'
      path: '/category/$category'
      fullPath: '/category/$category'
      preLoaderRoute: typeof CategoryCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$product': {
      id: '/product/$product'
      path: '/product/$product'
      fullPath: '/product/$product'
      preLoaderRoute: typeof ProductProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/me': {
      id: '/api/account/me'
      path: '/api/account/me'
      fullPath: '/api/account/me'
      preLoaderRoute: typeof ApiAccountMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/wishlist': {
      id: '/api/account/wishlist'
      path: '/api/account/wishlist'
      fullPath: '/api/account/wishlist'
      preLoaderRoute: typeof ApiAccountWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/inventory': {
      id: '/api/admin/inventory'
      path: '/api/admin/inventory'
      fullPath: '/api/admin/inventory'
      preLoaderRoute: typeof ApiAdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/overview': {
      id: '/api/admin/overview'
      path: '/api/admin/overview'
      fullPath: '/api/admin/overview'
      preLoaderRoute: typeof ApiAdminOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profile': {
      id: '/api/auth/profile'
      path: '/api/auth/profile'
      fullPath: '/api/auth/profile'
      preLoaderRoute: typeof ApiAuthProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/purchase': {
      id: '/api/inventory/purchase'
      path: '/api/inventory/purchase'
      fullPath: '/api/inventory/purchase'
      preLoaderRoute: typeof ApiInventoryPurchaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/login': {
      id: '/api/admin/auth/login'
      path: '/api/admin/auth/login'
      fullPath: '/api/admin/auth/login'
      preLoaderRoute: typeof ApiAdminAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/logout': {
      id: '/api/admin/auth/logout'
      path: '/api/admin/auth/logout'
      fullPath: '/api/admin/auth/logout'
      preLoaderRoute: typeof ApiAdminAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/me': {
      id: '/api/admin/auth/me'
      path: '/api/admin/auth/me'
      fullPath: '/api/admin/auth/me'
      preLoaderRoute: typeof ApiAdminAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/setup': {
      id: '/api/admin/auth/setup'
      path: '/api/admin/auth/setup'
      fullPath: '/api/admin/auth/setup'
      preLoaderRoute: typeof ApiAdminAuthSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/status': {
      id: '/api/admin/auth/status'
      path: '/api/admin/auth/status'
      fullPath: '/api/admin/auth/status'
      preLoaderRoute: typeof ApiAdminAuthStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/brands/': {
      id: '/api/admin/brands/'
      path: '/api/admin/brands'
      fullPath: '/api/admin/brands/'
      preLoaderRoute: typeof ApiAdminBrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/brands/$brandId': {
      id: '/api/admin/brands/$brandId'
      path: '/api/admin/brands/$brandId'
      fullPath: '/api/admin/brands/$brandId'
      preLoaderRoute: typeof ApiAdminBrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories/': {
      id: '/api/admin/categories/'
      path: '/api/admin/categories'
      fullPath: '/api/admin/categories/'
      preLoaderRoute: typeof ApiAdminCategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories/$categoryId': {
      id: '/api/admin/categories/$categoryId'
      path: '/api/admin/categories/$categoryId'
      fullPath: '/api/admin/categories/$categoryId'
      preLoaderRoute: typeof ApiAdminCategoriesCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories/reorder': {
      id: '/api/admin/categories/reorder'
      path: '/api/admin/categories/reorder'
      fullPath: '/api/admin/categories/reorder'
      preLoaderRoute: typeof ApiAdminCategoriesReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/inventory/$movementId': {
      id: '/api/admin/inventory/$movementId'
      path: '/$movementId'
      fullPath: '/api/admin/inventory/$movementId'
      preLoaderRoute: typeof ApiAdminInventoryMovementIdRouteImport
      parentRoute: typeof ApiAdminInventoryRoute
    }
    '/api/admin/products/': {
      id: '/api/admin/products/'
      path: '/api/admin/products'
      fullPath: '/api/admin/products/'
      preLoaderRoute: typeof ApiAdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/products/$productId': {
      id: '/api/admin/products/$productId'
      path: '/api/admin/products/$productId'
      fullPath: '/api/admin/products/$productId'
      preLoaderRoute: typeof ApiAdminProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSetupRoute: typeof AdminSetupRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSetupRoute: AdminSetupRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ApiAdminInventoryRouteChildren {
  ApiAdminInventoryMovementIdRoute: typeof ApiAdminInventoryMovementIdRoute
}

const ApiAdminInventoryRouteChildren: ApiAdminInventoryRouteChildren = {
  ApiAdminInventoryMovementIdRoute: ApiAdminInventoryMovementIdRoute,
}

const ApiAdminInventoryRouteWithChildren =
  ApiAdminInventoryRoute._addFileChildren(ApiAdminInventoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  OrderRoute: OrderRoute,
  ProfileRoute: ProfileRoute,
  CategoryCategoryRoute: CategoryCategoryRoute,
  ProductProductRoute: ProductProductRoute,
  ApiAccountMeRoute: ApiAccountMeRoute,
  ApiAccountWishlistRoute: ApiAccountWishlistRoute,
  ApiAdminInventoryRoute: ApiAdminInventoryRouteWithChildren,
  ApiAdminOverviewRoute: ApiAdminOverviewRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthProfileRoute: ApiAuthProfileRoute,
  ApiInventoryPurchaseRoute: ApiInventoryPurchaseRoute,
  ApiAdminAuthLoginRoute: ApiAdminAuthLoginRoute,
  ApiAdminAuthLogoutRoute: ApiAdminAuthLogoutRoute,
  ApiAdminAuthMeRoute: ApiAdminAuthMeRoute,
  ApiAdminAuthSetupRoute: ApiAdminAuthSetupRoute,
  ApiAdminAuthStatusRoute: ApiAdminAuthStatusRoute,
  ApiAdminBrandsBrandIdRoute: ApiAdminBrandsBrandIdRoute,
  ApiAdminCategoriesCategoryIdRoute: ApiAdminCategoriesCategoryIdRoute,
  ApiAdminCategoriesReorderRoute: ApiAdminCategoriesReorderRoute,
  ApiAdminProductsProductIdRoute: ApiAdminProductsProductIdRoute,
  ApiAdminBrandsIndexRoute: ApiAdminBrandsIndexRoute,
  ApiAdminCategoriesIndexRoute: ApiAdminCategoriesIndexRoute,
  ApiAdminProductsIndexRoute: ApiAdminProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
